name: Updatable Comment
description: Update comments as your workflow runs.
author: Drew Wyatt <drew.j.wyatt@gmail.com>
inputs:
  id:
    required: false
    description: If not supplied, this action will generate one for you.
  comment:
    required: true
    description: The comment body
  github-token:
    required: true
    description: Github token
outputs:
  id:
    description: The supplied or generated comment id (for future updates)
runs:
  using: 'node16'
  main: 'dist/index.js'
